/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atividade5;

/**
 *
 * @author tiago
 */
public class FotoGrupo extends javax.swing.JFrame {

    /**
     * Creates new form FotoGrupo
     */
    public FotoGrupo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialogFoto = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabelArtista1 = new javax.swing.JLabel();
        jLabelColegial1 = new javax.swing.JLabel();
        jLabelJardineira1 = new javax.swing.JLabel();
        jLabelSurfista1 = new javax.swing.JLabel();
        jLabelTenista1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelArtista = new javax.swing.JLabel();
        jLabelColegial = new javax.swing.JLabel();
        jLabelJardineira = new javax.swing.JLabel();
        jLabelSurfista = new javax.swing.JLabel();
        jLabelTenista = new javax.swing.JLabel();
        jButtonFoto = new javax.swing.JButton();
        jCheckBoxTodas = new javax.swing.JCheckBox();
        jCheckBoxNenhuma = new javax.swing.JCheckBox();
        jCheckBoxTenista = new javax.swing.JCheckBox();
        jCheckBoxSurfista = new javax.swing.JCheckBox();
        jCheckBoxJardineira = new javax.swing.JCheckBox();
        jCheckBoxColegial = new javax.swing.JCheckBox();
        jCheckBoxArtista = new javax.swing.JCheckBox();

        jDialogFoto.setMinimumSize(new java.awt.Dimension(570, 380));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelArtista1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensGirls/artista.jpg"))); // NOI18N
        jLabelArtista1.setText("Artista");

        jLabelColegial1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensGirls/colegial.jpg"))); // NOI18N
        jLabelColegial1.setText("Colegial");

        jLabelJardineira1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensGirls/jardineira.gif"))); // NOI18N
        jLabelJardineira1.setText("jLabel1");

        jLabelSurfista1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensGirls/surfista.jpg"))); // NOI18N
        jLabelSurfista1.setText("jLabel1");

        jLabelTenista1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensGirls/tenista.jpg"))); // NOI18N
        jLabelTenista1.setText("Tenista");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelArtista1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabelColegial1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelJardineira1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelSurfista1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabelTenista1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTenista1)
                            .addComponent(jLabelSurfista1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelJardineira1)
                            .addComponent(jLabelColegial1)
                            .addComponent(jLabelArtista1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogFotoLayout = new javax.swing.GroupLayout(jDialogFoto.getContentPane());
        jDialogFoto.getContentPane().setLayout(jDialogFotoLayout);
        jDialogFotoLayout.setHorizontalGroup(
            jDialogFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jDialogFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogFotoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jDialogFotoLayout.setVerticalGroup(
            jDialogFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jDialogFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogFotoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelArtista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensGirls/artista.jpg"))); // NOI18N
        jLabelArtista.setText("Artista");

        jLabelColegial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensGirls/colegial.jpg"))); // NOI18N
        jLabelColegial.setText("Colegial");

        jLabelJardineira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensGirls/jardineira.gif"))); // NOI18N
        jLabelJardineira.setText("jLabel1");

        jLabelSurfista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensGirls/surfista.jpg"))); // NOI18N
        jLabelSurfista.setText("jLabel1");

        jLabelTenista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensGirls/tenista.jpg"))); // NOI18N
        jLabelTenista.setText("Tenista");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabelColegial, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelJardineira, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelSurfista, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabelTenista, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTenista)
                            .addComponent(jLabelSurfista)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelJardineira)
                            .addComponent(jLabelColegial)
                            .addComponent(jLabelArtista))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonFoto.setText("Foto");
        jButtonFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFotoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckBoxTodas);
        jCheckBoxTodas.setText("Todas");
        jCheckBoxTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTodasActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckBoxNenhuma);
        jCheckBoxNenhuma.setText("Nenhuma");
        jCheckBoxNenhuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNenhumaActionPerformed(evt);
            }
        });

        jCheckBoxTenista.setText("Tenista");
        jCheckBoxTenista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTenistaActionPerformed(evt);
            }
        });

        jCheckBoxSurfista.setText("Surfista");

        jCheckBoxJardineira.setText("Jardineira");

        jCheckBoxColegial.setText("Colegial");

        jCheckBoxArtista.setText("Artista");
        jCheckBoxArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxArtistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jCheckBoxArtista)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxColegial)
                            .addComponent(jCheckBoxTodas))
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxSurfista)
                                .addGap(89, 89, 89)
                                .addComponent(jCheckBoxTenista))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jCheckBoxNenhuma))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxJardineira))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxArtista)
                    .addComponent(jCheckBoxColegial)
                    .addComponent(jCheckBoxSurfista)
                    .addComponent(jCheckBoxJardineira)
                    .addComponent(jCheckBoxTenista))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxNenhuma)
                    .addComponent(jCheckBoxTodas))
                .addGap(18, 18, 18)
                .addComponent(jButtonFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxArtistaActionPerformed

    private void jCheckBoxTenistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTenistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTenistaActionPerformed

    private void jCheckBoxTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTodasActionPerformed
      jCheckBoxArtista.setSelected(true);          
      jCheckBoxColegial.setSelected(true);          
      jCheckBoxJardineira.setSelected(true);         
      jCheckBoxSurfista.setSelected(true);          
      jCheckBoxTenista.setSelected(true); 
    }//GEN-LAST:event_jCheckBoxTodasActionPerformed

    private void jCheckBoxNenhumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNenhumaActionPerformed
      jCheckBoxArtista.setSelected(false); 
      jCheckBoxColegial.setSelected(false); 
      jCheckBoxJardineira.setSelected(false); 
      jCheckBoxSurfista.setSelected(false); 
      jCheckBoxTenista.setSelected(false); 
    }//GEN-LAST:event_jCheckBoxNenhumaActionPerformed

    private void jButtonFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFotoActionPerformed
        jDialogFoto.setVisible(true); 
        jLabelArtista1.setVisible(jCheckBoxArtista.isSelected());        
        jLabelColegial1.setVisible(jCheckBoxColegial.isSelected());         
        jLabelJardineira1.setVisible(jCheckBoxJardineira.isSelected()); 
        jLabelSurfista1.setVisible(jCheckBoxSurfista.isSelected());         
        jLabelTenista1.setVisible(jCheckBoxTenista.isSelected());         
        jDialogFoto.setVisible(true); 
    }//GEN-LAST:event_jButtonFotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FotoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FotoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FotoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FotoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FotoGrupo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonFoto;
    private javax.swing.JCheckBox jCheckBoxArtista;
    private javax.swing.JCheckBox jCheckBoxColegial;
    private javax.swing.JCheckBox jCheckBoxJardineira;
    private javax.swing.JCheckBox jCheckBoxNenhuma;
    private javax.swing.JCheckBox jCheckBoxSurfista;
    private javax.swing.JCheckBox jCheckBoxTenista;
    private javax.swing.JCheckBox jCheckBoxTodas;
    private javax.swing.JDialog jDialogFoto;
    private javax.swing.JLabel jLabelArtista;
    private javax.swing.JLabel jLabelArtista1;
    private javax.swing.JLabel jLabelColegial;
    private javax.swing.JLabel jLabelColegial1;
    private javax.swing.JLabel jLabelJardineira;
    private javax.swing.JLabel jLabelJardineira1;
    private javax.swing.JLabel jLabelSurfista;
    private javax.swing.JLabel jLabelSurfista1;
    private javax.swing.JLabel jLabelTenista;
    private javax.swing.JLabel jLabelTenista1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
