/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atividade4;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent; 
import javax.swing.Timer; 
/**
 *
 * @author tiago
 */
public class Animaçao extends javax.swing.JFrame {

    /**
     * Creates new form Animaçao
     */
    Timer timer ;
    private int valor=0;

    
    public Animaçao() {
        initComponents();
        jLabelDuke1.setVisible(false);
        jLabelDuke2.setVisible(false);
        jLabelDuke3.setVisible(false);
        jLabelDuke4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelDuke1 = new javax.swing.JLabel();
        jLabelDuke2 = new javax.swing.JLabel();
        jLabelDuke3 = new javax.swing.JLabel();
        jLabelDuke4 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButtonIniciar = new javax.swing.JButton();
        jButtonParar = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Animação Duke");

        jPanel1.setLayout(null);

        jLabelDuke1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensDuke/zip/duke_flip4.gif"))); // NOI18N
        jLabelDuke1.setText("jLabel1");
        jPanel1.add(jLabelDuke1);
        jLabelDuke1.setBounds(70, 20, 60, 60);

        jLabelDuke2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensDuke/zip/duke_flip1.gif"))); // NOI18N
        jLabelDuke2.setText("jLabel2");
        jPanel1.add(jLabelDuke2);
        jLabelDuke2.setBounds(260, 20, 60, 60);

        jLabelDuke3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensDuke/zip/duke_flip2.gif"))); // NOI18N
        jLabelDuke3.setText("jLabel3");
        jPanel1.add(jLabelDuke3);
        jLabelDuke3.setBounds(200, 20, 60, 60);

        jLabelDuke4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensDuke/zip/duke_flip3.gif"))); // NOI18N
        jLabelDuke4.setText("jLabel4");
        jPanel1.add(jLabelDuke4);
        jLabelDuke4.setBounds(140, 20, 60, 60);

        jProgressBar1.setStringPainted(true);
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(120, 100, 146, 17);

        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.setToolTipText("Clique para iniciar ");
        jButtonIniciar.setActionCommand("jButtonIniciar");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonIniciar);
        jButtonIniciar.setBounds(60, 140, 80, 30);

        jButtonParar.setText("Parar");
        jButtonParar.setToolTipText("Clique para parar ");
        jButtonParar.setActionCommand("jButtonParar");
        jButtonParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPararActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonParar);
        jButtonParar.setBounds(220, 140, 80, 30);

        jSlider1.setMajorTickSpacing(10);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setToolTipText(" Ajustar a velocidade ");
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jPanel1.add(jSlider1);
        jSlider1.setBounds(80, 190, 220, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        if (timer == null){             
            criarTimer();             
            timer.start(); }
        else if (!timer.isRunning()) timer.restart(); 
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jButtonPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPararActionPerformed
        timer.stop();
    }//GEN-LAST:event_jButtonPararActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
    int valorSlider = jSlider1.getValue(); 
    timer.setDelay(valor=10);
    }//GEN-LAST:event_jSlider1StateChanged

    /**
     * @param args the command line arguments
     */
 private void criarTimer(){         
        timer = new javax.swing.Timer(1000, new ActionListener() {             
        public void actionPerformed(ActionEvent e) {                 
        tarefa();             
        }         
      });     
} 
private void tarefa(){         
    jLabelDuke1.setVisible(valor % 4 == 0);         
    jLabelDuke2.setVisible(valor % 4 == 1);         
    jLabelDuke3.setVisible(valor % 4 == 2); 
    jLabelDuke4.setVisible(valor % 4 == 3);         
    valor ++;         
    jProgressBar1.setValue(valor);         
    if (valor >= 100){             
        valor = 0;             
        timer.stop();         
    }     
} 
    
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Animaçao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Animaçao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Animaçao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Animaçao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Animaçao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonParar;
    private javax.swing.JLabel jLabelDuke1;
    private javax.swing.JLabel jLabelDuke2;
    private javax.swing.JLabel jLabelDuke3;
    private javax.swing.JLabel jLabelDuke4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
