/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula21mar2018auto;

import java.awt.Color;

/**
 *
 * @author Tiago
 */
public class AppAuto extends javax.swing.JFrame {

    /**
     * Creates new form AppAuto
     */
    public AppAuto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVisor = new javax.swing.JPanel();
        jLabelVelocidade = new javax.swing.JLabel();
        jLabelMudanca = new javax.swing.JLabel();
        jLabelunidadedeVelocidade = new javax.swing.JLabel();
        jLabelDeposito = new javax.swing.JLabel();
        jLabelReserva = new javax.swing.JLabel();
        jLabelunidadedeVelocidade1 = new javax.swing.JLabel();
        jButtonMudancaMais = new javax.swing.JButton();
        jButtonMudancaMenos = new javax.swing.JButton();
        jButtonTravar = new javax.swing.JButton();
        jButtonAcelerar = new javax.swing.JButton();
        jButtonStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Auto");
        setBackground(new java.awt.Color(0, 0, 0));

        jPanelVisor.setBackground(new java.awt.Color(204, 204, 255));
        jPanelVisor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelVisor.setForeground(new java.awt.Color(102, 102, 102));

        jLabelVelocidade.setBackground(new java.awt.Color(255, 255, 255));
        jLabelVelocidade.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelVelocidade.setForeground(new java.awt.Color(51, 51, 255));
        jLabelVelocidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVelocidade.setText("0");
        jLabelVelocidade.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelMudanca.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMudanca.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelMudanca.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMudanca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMudanca.setText("0");
        jLabelMudanca.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelunidadedeVelocidade.setForeground(new java.awt.Color(255, 255, 255));
        jLabelunidadedeVelocidade.setText("km/h");

        jLabelDeposito.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDeposito.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelDeposito.setForeground(new java.awt.Color(255, 255, 0));
        jLabelDeposito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDeposito.setText("60");

        jLabelReserva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelReserva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReserva.setText("R");

        jLabelunidadedeVelocidade1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelunidadedeVelocidade1.setText("combustivel");

        jButtonMudancaMais.setBackground(new java.awt.Color(0, 0, 0));
        jButtonMudancaMais.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonMudancaMais.setForeground(new java.awt.Color(0, 204, 204));
        jButtonMudancaMais.setText("+");
        jButtonMudancaMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMudancaMaisActionPerformed(evt);
            }
        });

        jButtonMudancaMenos.setBackground(new java.awt.Color(255, 0, 0));
        jButtonMudancaMenos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonMudancaMenos.setForeground(new java.awt.Color(255, 255, 0));
        jButtonMudancaMenos.setText("-");
        jButtonMudancaMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMudancaMenosActionPerformed(evt);
            }
        });

        jButtonTravar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonTravar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonTravar.setForeground(new java.awt.Color(255, 0, 0));
        jButtonTravar.setText("Travar");
        jButtonTravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTravarActionPerformed(evt);
            }
        });

        jButtonAcelerar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAcelerar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAcelerar.setForeground(new java.awt.Color(0, 204, 204));
        jButtonAcelerar.setText("Acelerar");
        jButtonAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcelerarActionPerformed(evt);
            }
        });

        jButtonStart.setBackground(new java.awt.Color(0, 0, 0));
        jButtonStart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonStart.setText("Start");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVisorLayout = new javax.swing.GroupLayout(jPanelVisor);
        jPanelVisor.setLayout(jPanelVisorLayout);
        jPanelVisorLayout.setHorizontalGroup(
            jPanelVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVisorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelVisorLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabelMudanca, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonMudancaMenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMudancaMais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanelVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVisorLayout.createSequentialGroup()
                        .addComponent(jLabelVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelunidadedeVelocidade)
                        .addGap(23, 23, 23)
                        .addComponent(jLabelReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelVisorLayout.createSequentialGroup()
                        .addComponent(jButtonTravar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAcelerar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVisorLayout.createSequentialGroup()
                        .addComponent(jLabelDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelunidadedeVelocidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanelVisorLayout.setVerticalGroup(
            jPanelVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVisorLayout.createSequentialGroup()
                .addGroup(jPanelVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVisorLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanelVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMudanca)
                            .addComponent(jLabelunidadedeVelocidade1)))
                    .addGroup(jPanelVisorLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanelVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelunidadedeVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanelVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVisorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelVisorLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButtonTravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelVisorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMudancaMais, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMudancaMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanelVisorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAcelerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelVisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelVisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(522, 382));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        if (fiat.isEstado()) {
            if (fiat.getVelocidade() <= 0) {
                fiat.desligar();
                jButtonStart.setText("Start");
                jPanelVisor.setBackground(new java.awt.Color(153, 153, 153));
            }
        } else {
            fiat.ligar();
            jButtonStart.setText("Stop");
            jPanelVisor.setBackground(new java.awt.Color(0, 0, 0));
        }


    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonMudancaMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMudancaMaisActionPerformed
        fiat.mudancaMais();
        jLabelMudanca.setText("" + fiat.getMudanca());
    }//GEN-LAST:event_jButtonMudancaMaisActionPerformed

    private void jButtonMudancaMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMudancaMenosActionPerformed
        fiat.mudancaMenos();
        if (fiat.getMudanca() == -1) {
            jLabelMudanca.setText("R");
        } else {
            jLabelMudanca.setText("" + fiat.getMudanca());
        }
    }//GEN-LAST:event_jButtonMudancaMenosActionPerformed

    private void jButtonAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcelerarActionPerformed
        fiat.acelerar();
        if (20 > fiat.getCombustivel()) {
            jLabelReserva.setText("R");
            jLabelReserva.setForeground(new java.awt.Color(255, 0, 0));
        }
        jLabelVelocidade.setText("" + fiat.getVelocidade());
        jLabelDeposito.setText("" + fiat.getCombustivel());
    }//GEN-LAST:event_jButtonAcelerarActionPerformed

    private void jButtonTravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTravarActionPerformed
        fiat.travar();
        jLabelVelocidade.setText("" + fiat.getVelocidade());
    }//GEN-LAST:event_jButtonTravarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppAuto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcelerar;
    private javax.swing.JButton jButtonMudancaMais;
    private javax.swing.JButton jButtonMudancaMenos;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonTravar;
    private javax.swing.JLabel jLabelDeposito;
    private javax.swing.JLabel jLabelMudanca;
    private javax.swing.JLabel jLabelReserva;
    private javax.swing.JLabel jLabelVelocidade;
    private javax.swing.JLabel jLabelunidadedeVelocidade;
    private javax.swing.JLabel jLabelunidadedeVelocidade1;
    private javax.swing.JPanel jPanelVisor;
    // End of variables declaration//GEN-END:variables
    Auto fiat = new Auto();
}
