/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atividade.pkg05;

/**
 *
 * @author tiago
 */
public class FotoGrupo extends javax.swing.JFrame {

    /**
     * Creates new form FotoGrupo
     */
    public FotoGrupo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialogFoto = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabelArtista2 = new javax.swing.JLabel();
        jLabelColegial2 = new javax.swing.JLabel();
        jLabelJardineira2 = new javax.swing.JLabel();
        jLabelSurfista2 = new javax.swing.JLabel();
        jLabelTenista2 = new javax.swing.JLabel();
        jCheckBoxArtista2 = new javax.swing.JCheckBox();
        jCheckBoxColegial2 = new javax.swing.JCheckBox();
        jCheckBoxJardineira2 = new javax.swing.JCheckBox();
        jCheckBoxSurfista2 = new javax.swing.JCheckBox();
        jCheckBoxTenista2 = new javax.swing.JCheckBox();
        jCheckBoxTodas2 = new javax.swing.JCheckBox();
        jCheckBoxNenhuma2 = new javax.swing.JCheckBox();
        jButtonFoto2 = new javax.swing.JButton();
        jPanel = new javax.swing.JPanel();
        jLabelArtista = new javax.swing.JLabel();
        jLabelColegial = new javax.swing.JLabel();
        jLabelJardineira = new javax.swing.JLabel();
        jLabelSurfista = new javax.swing.JLabel();
        jLabelTenista = new javax.swing.JLabel();
        jCheckBoxArtista = new javax.swing.JCheckBox();
        jCheckBoxColegial = new javax.swing.JCheckBox();
        jCheckBoxJardineira = new javax.swing.JCheckBox();
        jCheckBoxSurfista = new javax.swing.JCheckBox();
        jCheckBoxTenista = new javax.swing.JCheckBox();
        jCheckBoxTodas = new javax.swing.JCheckBox();
        jCheckBoxNenhuma = new javax.swing.JCheckBox();
        jButtonFoto = new javax.swing.JButton();

        jDialogFoto.setMinimumSize(new java.awt.Dimension(570, 380));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelArtista2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensGirls/artista.jpg"))); // NOI18N
        jLabelArtista2.setText("jLabel1");

        jLabelColegial2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensGirls/colegial.jpg"))); // NOI18N
        jLabelColegial2.setText("jLabel2");

        jLabelJardineira2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensGirls/jardineira.gif"))); // NOI18N
        jLabelJardineira2.setText("jLabel1");

        jLabelSurfista2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensGirls/surfista.jpg"))); // NOI18N
        jLabelSurfista2.setText("jLabel1");

        jLabelTenista2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensGirls/tenista.jpg"))); // NOI18N
        jLabelTenista2.setText("jLabel1");

        jCheckBoxArtista2.setText("Artista");

        jCheckBoxColegial2.setText("Colegial");

        jCheckBoxJardineira2.setText("Jardineira");

        jCheckBoxSurfista2.setText("Surfista");

        jCheckBoxTenista2.setText("Tenista");

        buttonGroup1.add(jCheckBoxTodas2);
        jCheckBoxTodas2.setText("Todas");
        jCheckBoxTodas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTodas2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckBoxNenhuma2);
        jCheckBoxNenhuma2.setText("Nenhuma");
        jCheckBoxNenhuma2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNenhuma2ActionPerformed(evt);
            }
        });

        jButtonFoto2.setText("Foto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelArtista2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxArtista2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelColegial2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxColegial2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelJardineira2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxJardineira2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSurfista2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxSurfista2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxTenista2)
                    .addComponent(jLabelTenista2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jCheckBoxTodas2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFoto2)
                .addGap(91, 91, 91)
                .addComponent(jCheckBoxNenhuma2)
                .addGap(250, 250, 250))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelArtista2)
                    .addComponent(jLabelColegial2)
                    .addComponent(jLabelJardineira2)
                    .addComponent(jLabelSurfista2)
                    .addComponent(jLabelTenista2))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxArtista2)
                    .addComponent(jCheckBoxColegial2)
                    .addComponent(jCheckBoxJardineira2)
                    .addComponent(jCheckBoxSurfista2)
                    .addComponent(jCheckBoxTenista2))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTodas2)
                    .addComponent(jCheckBoxNenhuma2)
                    .addComponent(jButtonFoto2))
                .addContainerGap(237, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogFotoLayout = new javax.swing.GroupLayout(jDialogFoto.getContentPane());
        jDialogFoto.getContentPane().setLayout(jDialogFotoLayout);
        jDialogFotoLayout.setHorizontalGroup(
            jDialogFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogFotoLayout.setVerticalGroup(
            jDialogFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogFotoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelArtista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensGirls/artista.jpg"))); // NOI18N
        jLabelArtista.setText("jLabel1");

        jLabelColegial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensGirls/colegial.jpg"))); // NOI18N
        jLabelColegial.setText("jLabel2");

        jLabelJardineira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensGirls/jardineira.gif"))); // NOI18N
        jLabelJardineira.setText("jLabel1");

        jLabelSurfista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensGirls/surfista.jpg"))); // NOI18N
        jLabelSurfista.setText("jLabel1");

        jLabelTenista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensGirls/tenista.jpg"))); // NOI18N
        jLabelTenista.setText("jLabel1");

        jCheckBoxArtista.setText("Artista");

        jCheckBoxColegial.setText("Colegial");

        jCheckBoxJardineira.setText("Jardineira");

        jCheckBoxSurfista.setText("Surfista");

        jCheckBoxTenista.setText("Tenista");

        buttonGroup1.add(jCheckBoxTodas);
        jCheckBoxTodas.setText("Todas");
        jCheckBoxTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTodasActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckBoxNenhuma);
        jCheckBoxNenhuma.setSelected(true);
        jCheckBoxNenhuma.setText("Nenhuma");
        jCheckBoxNenhuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNenhumaActionPerformed(evt);
            }
        });

        jButtonFoto.setText("Foto");
        jButtonFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxArtista))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelColegial, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxColegial))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelJardineira, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxJardineira))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSurfista, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxSurfista))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxTenista)
                    .addComponent(jLabelTenista, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jCheckBoxTodas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFoto)
                .addGap(91, 91, 91)
                .addComponent(jCheckBoxNenhuma)
                .addGap(250, 250, 250))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelArtista)
                    .addComponent(jLabelColegial)
                    .addComponent(jLabelJardineira)
                    .addComponent(jLabelSurfista)
                    .addComponent(jLabelTenista))
                .addGap(34, 34, 34)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxArtista)
                    .addComponent(jCheckBoxColegial)
                    .addComponent(jCheckBoxJardineira)
                    .addComponent(jCheckBoxSurfista)
                    .addComponent(jCheckBoxTenista))
                .addGap(44, 44, 44)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTodas)
                    .addComponent(jCheckBoxNenhuma)
                    .addComponent(jButtonFoto))
                .addContainerGap(237, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTodasActionPerformed
 jCheckBoxArtista.setSelected(true);
 jCheckBoxColegial.setSelected(true);
 jCheckBoxJardineira.setSelected(true);
 jCheckBoxSurfista.setSelected(true);
 jCheckBoxTenista.setSelected(true);
    }//GEN-LAST:event_jCheckBoxTodasActionPerformed

    private void jCheckBoxNenhumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNenhumaActionPerformed
jCheckBoxArtista.setSelected(false);
jCheckBoxColegial.setSelected(false);
jCheckBoxJardineira.setSelected(false);
jCheckBoxSurfista.setSelected(false);
jCheckBoxTenista.setSelected(false); 
    }//GEN-LAST:event_jCheckBoxNenhumaActionPerformed

    private void jCheckBoxTodas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTodas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTodas2ActionPerformed

    private void jCheckBoxNenhuma2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNenhuma2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxNenhuma2ActionPerformed

    private void jButtonFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFotoActionPerformed
        jDialogFoto.setVisible(true);
         jLabelArtista1.setVisible(jCheckBoxArtista.isSelected());
         jLabelColegial1.setVisible(jCheckBoxColegial.isSelected());
         jLabelJardineira1.setVisible(jCheckBoxJardineira.isSelected());
           jLabelSurfista1.setVisible(jCheckBoxSurfista.isSelected());
           jLabelTenista1.setVisible(jCheckBoxTenista.isSelected());
           jDialogFoto.setVisible(true); 
    }//GEN-LAST:event_jButtonFotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FotoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FotoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FotoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FotoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FotoGrupo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonFoto;
    private javax.swing.JButton jButtonFoto1;
    private javax.swing.JButton jButtonFoto2;
    private javax.swing.JCheckBox jCheckBoxArtista;
    private javax.swing.JCheckBox jCheckBoxArtista1;
    private javax.swing.JCheckBox jCheckBoxArtista2;
    private javax.swing.JCheckBox jCheckBoxColegial;
    private javax.swing.JCheckBox jCheckBoxColegial1;
    private javax.swing.JCheckBox jCheckBoxColegial2;
    private javax.swing.JCheckBox jCheckBoxJardineira;
    private javax.swing.JCheckBox jCheckBoxJardineira1;
    private javax.swing.JCheckBox jCheckBoxJardineira2;
    private javax.swing.JCheckBox jCheckBoxNenhuma;
    private javax.swing.JCheckBox jCheckBoxNenhuma1;
    private javax.swing.JCheckBox jCheckBoxNenhuma2;
    private javax.swing.JCheckBox jCheckBoxSurfista;
    private javax.swing.JCheckBox jCheckBoxSurfista1;
    private javax.swing.JCheckBox jCheckBoxSurfista2;
    private javax.swing.JCheckBox jCheckBoxTenista;
    private javax.swing.JCheckBox jCheckBoxTenista1;
    private javax.swing.JCheckBox jCheckBoxTenista2;
    private javax.swing.JCheckBox jCheckBoxTodas;
    private javax.swing.JCheckBox jCheckBoxTodas1;
    private javax.swing.JCheckBox jCheckBoxTodas2;
    private javax.swing.JDialog jDialogFoto;
    private javax.swing.JLabel jLabelArtista;
    private javax.swing.JLabel jLabelArtista1;
    private javax.swing.JLabel jLabelArtista2;
    private javax.swing.JLabel jLabelColegial;
    private javax.swing.JLabel jLabelColegial1;
    private javax.swing.JLabel jLabelColegial2;
    private javax.swing.JLabel jLabelJardineira;
    private javax.swing.JLabel jLabelJardineira1;
    private javax.swing.JLabel jLabelJardineira2;
    private javax.swing.JLabel jLabelSurfista;
    private javax.swing.JLabel jLabelSurfista1;
    private javax.swing.JLabel jLabelSurfista2;
    private javax.swing.JLabel jLabelTenista;
    private javax.swing.JLabel jLabelTenista1;
    private javax.swing.JLabel jLabelTenista2;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
