/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maquinavendast2;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jfig
 */
public class AppMaquinaVenda extends javax.swing.JFrame {

    /**
     * Creates new form AppMaquinaVenda
     */
    public AppMaquinaVenda() {
        initComponents();
    }
    static int count = 0;

    private int conta() {
        count++;
        return count;
    }

    static int count2 = 0;

    private int conta2() {
        count2++;
        return count2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogTalao = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaTalao = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButtonAgua = new javax.swing.JButton();
        jButtonCafe = new javax.swing.JButton();
        jButtonCompal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonMais = new javax.swing.JButton();
        jButtonMenos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        jButtonAnular = new javax.swing.JButton();
        jButtonTalao = new javax.swing.JButton();
        jLabelTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jDialogTalao.setTitle("Talão");
        jDialogTalao.setLocationByPlatform(true);
        jDialogTalao.setMinimumSize(new java.awt.Dimension(310, 400));

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("BarEI Empresa");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTextAreaTalao.setColumns(20);
        jTextAreaTalao.setRows(5);
        jScrollPane2.setViewportView(jTextAreaTalao);

        javax.swing.GroupLayout jDialogTalaoLayout = new javax.swing.GroupLayout(jDialogTalao.getContentPane());
        jDialogTalao.getContentPane().setLayout(jDialogTalaoLayout);
        jDialogTalaoLayout.setHorizontalGroup(
            jDialogTalaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogTalaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogTalaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogTalaoLayout.setVerticalGroup(
            jDialogTalaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogTalaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Máquina de Venda");

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(null);

        jButtonAgua.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonAgua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensVenda/agua.jpg"))); // NOI18N
        jButtonAgua.setText("<html> Água <br> 0.50€ </html>");
        jButtonAgua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAgua.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAguaActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAgua);
        jButtonAgua.setBounds(10, 11, 72, 107);

        jButtonCafe.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonCafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensVenda/cafe.jpg"))); // NOI18N
        jButtonCafe.setText("<html> Café <br> 0.40€ </html>");
        jButtonCafe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCafe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCafeActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCafe);
        jButtonCafe.setBounds(10, 129, 72, 112);

        jButtonCompal.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonCompal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensVenda/sumo.jpg"))); // NOI18N
        jButtonCompal.setText("<html> Compal <br> 0.60€ </html>");
        jButtonCompal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCompal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCompal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompalActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCompal);
        jButtonCompal.setBounds(88, 11, 72, 107);

        jTabbedPane1.addTab("Bebidas", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Comida", jPanel3);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonMais.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonMais.setText("+");
        jButtonMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaisActionPerformed(evt);
            }
        });

        jButtonMenos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonMenos.setText("-");
        jButtonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosActionPerformed(evt);
            }
        });

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quantidade", "Produto", "SubTotal"
            }
        ));
        jScrollPane1.setViewportView(jTableProdutos);

        jButtonAnular.setBackground(new java.awt.Color(204, 0, 0));
        jButtonAnular.setText("Anular");
        jButtonAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnularActionPerformed(evt);
            }
        });

        jButtonTalao.setBackground(new java.awt.Color(0, 153, 0));
        jButtonTalao.setText("<html> Imprimir <br> Talão </html>");
        jButtonTalao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTalaoActionPerformed(evt);
            }
        });

        jLabelTotal.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotal.setText("0");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("Total:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonMais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAnular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(jButtonTalao)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTotal)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonMais, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTalao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(416, 489));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAguaActionPerformed
        String produto = "Água";
        double preco = 0.5;
        try {
            adicionaProduto(produto, preco);
        } catch (IOException ex) {
            Logger.getLogger(AppMaquinaVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAguaActionPerformed

    private void jButtonCompalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompalActionPerformed
        String produto = "Compal";
        double preco = 0.6;
        try {
            adicionaProduto(produto, preco);
        } catch (IOException ex) {
            Logger.getLogger(AppMaquinaVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCompalActionPerformed

    private void jButtonCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCafeActionPerformed
        String produto = "Café";
        double preco = 0.4;
        try {
            adicionaProduto(produto, preco);
        } catch (IOException ex) {
            Logger.getLogger(AppMaquinaVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCafeActionPerformed

    private void jButtonMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaisActionPerformed
        int linha = jTableProdutos.getSelectedRow();
        if (linha >= 0) {
            int quantidade = (int) jTableProdutos.getValueAt(linha, 0);
            double preco = (double) jTableProdutos.getValueAt(linha, 2);
            double precoUnitario = preco / quantidade;
            quantidade++;
            double valor = precoUnitario * quantidade;
            jTableProdutos.setValueAt(quantidade, linha, 0);
            jTableProdutos.setValueAt(valor, linha, 2);
        }
        jLabelTotal.setText("" + calcularTotal());
    }//GEN-LAST:event_jButtonMaisActionPerformed

    private void jButtonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosActionPerformed
        int linha = jTableProdutos.getSelectedRow();
        if (linha >= 0) {
            int quantidade = (int) jTableProdutos.getValueAt(linha, 0);
            double preco = (double) jTableProdutos.getValueAt(linha, 2);
            double precoUnitario = preco / quantidade;
            if (quantidade > 1) {
                quantidade--;
            }
            double valor = precoUnitario * quantidade;
            jTableProdutos.setValueAt(quantidade, linha, 0);
            jTableProdutos.setValueAt(valor, linha, 2);
        }
        jLabelTotal.setText("" + calcularTotal());
    }//GEN-LAST:event_jButtonMenosActionPerformed

    private void jButtonAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnularActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTableProdutos.getModel();
        int linha = jTableProdutos.getSelectedRow();
        if (linha >= 0) {
            modelo.removeRow(linha);
        } else {
            modelo.setRowCount(0);
        }
        jLabelTotal.setText("" + calcularTotal());
    }//GEN-LAST:event_jButtonAnularActionPerformed


    private void jButtonTalaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTalaoActionPerformed

        LocalDate hoje = LocalDate.now();
        LocalTime agora = LocalTime.now();

        try {
            FileWriter fw = new FileWriter("Talao" + conta() + ".txt");
            PrintWriter pw = new PrintWriter(fw);

            jTextAreaTalao.setText("");
            jTextAreaTalao.append("");
            pw.println("");
            jTextAreaTalao.append("" + hoje + " " + agora.getHour() + ":" + agora.getMinute() + ":" + agora.getSecond() + "\tnº: " + conta2() + "\n");
            pw.println("" + hoje + " " + agora.getHour() + ":" + agora.getMinute() + ":" + agora.getSecond()  + "\n");
            jTextAreaTalao.append("\n\n\nQuantidade\tProdutos\tSubTotal\n");
            pw.println("\n\n\nQuantidade\tProdutos\tSubTotal\n");
            jTextAreaTalao.append("------------------------------------------------------\n");
            pw.println("------------------------------------------------------\n");
            for (int i = 0; i < jTableProdutos.getRowCount(); i++) {
                int quantidade = (int) jTableProdutos.getValueAt(i, 0);
                String produto = jTableProdutos.getValueAt(i, 1).toString();
                double preco = (double) jTableProdutos.getValueAt(i, 2);
                String output = String.format("%3d\t%s\t%.2f\n",
                        quantidade, produto, preco);
                jTextAreaTalao.append(output);
                pw.println(output);
                jDialogTalao.setVisible(true);
                jTextAreaTalao.append("------------------------------------------------------\n");
            }
            pw.println("------------------------------------------------------\n");
            String output = String.format("%.2f €", calcularTotal());
            jTextAreaTalao.append("\n\tTotal a Pagar: " + output);
            pw.println("\n\t\tTotal a Pagar: " + output);

            pw.close();

        } catch (IOException ex) {
            Logger.getLogger(AppMaquinaVenda.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonTalaoActionPerformed

    private void adicionaProduto(String produto, double preco) throws IOException {
        DefaultTableModel modelo = (DefaultTableModel) jTableProdutos.getModel();
        
        System.out.println("" + jTableProdutos.getRowCount());
        String[] produtos;
        produtos = new String[20];
        int line = 0;
        if (jTableProdutos.getRowCount() > 0) {
            for (int i = 0; i < jTableProdutos.getRowCount(); i++) {
                if (produto == modelo.getValueAt(i, 1)) {
                    line = 1;
                    System.out.println("" + modelo.getValueAt(i, 1));
                    adicionaMaisProduto(i);

                }
            }

            if (line == 0) {
                Object[] rowData = {
                    1,
                    produto,
                    preco
                };
                modelo.addRow(rowData);
                jLabelTotal.setText("" + calcularTotal());
            }
        } else {
            Object[] rowData = {
                1,
                produto,
                preco
            };
            modelo.addRow(rowData);
            jLabelTotal.setText("" + calcularTotal());
        }
    }

    

    private double calcularTotal() {
        double total = 0;
        for (int i = 0; i < jTableProdutos.getRowCount(); i++) {
            double valor = (double) jTableProdutos.getValueAt(i, 2);
            total += valor;
        }
        return total;
    }

    private void adicionaMaisProduto(int selectRow) {
        int linha = selectRow;
        if (linha >= 0) {
            int quantidade = (int) jTableProdutos.getValueAt(linha, 0);
            double preco = (double) jTableProdutos.getValueAt(linha, 2);
            double precoUnitario = preco / quantidade;
            quantidade++;
            double valor = precoUnitario * quantidade;
            jTableProdutos.setValueAt(quantidade, linha, 0);
            jTableProdutos.setValueAt(valor, linha, 2);
        }
        jLabelTotal.setText("" + calcularTotal());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppMaquinaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppMaquinaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppMaquinaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppMaquinaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppMaquinaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgua;
    private javax.swing.JButton jButtonAnular;
    private javax.swing.JButton jButtonCafe;
    private javax.swing.JButton jButtonCompal;
    private javax.swing.JButton jButtonMais;
    private javax.swing.JButton jButtonMenos;
    private javax.swing.JButton jButtonTalao;
    private javax.swing.JDialog jDialogTalao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JTextArea jTextAreaTalao;
    // End of variables declaration//GEN-END:variables
}
